name: Deploy Portfolio

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install --save-dev html-validate stylelint stylelint-config-standard eslint eslint-config-standard

      - name: Validate HTML
        run: npx html-validate "index.html"

      - name: Validate CSS
        run: |
          if [ -d "assets/css" ]; then
            npx stylelint "assets/css/**/*.css"
          else
            echo "⚠️ No CSS directory found - skipping CSS validation"
          fi

      - name: Validate JavaScript
        run: |
          if [ -d "assets/js" ]; then
            npx eslint "assets/js/**/*.js"
          else
            echo "⚠️ No JS directory found - skipping JS validation"
          fi

      - name: Check required files
        run: |
          test -f index.html || (echo "❌ Missing index.html" && exit 1)
          test -d assets/css || echo "⚠️ Missing assets/css directory (optional but recommended)"
          test -d assets/js || echo "⚠️ Missing assets/js directory (optional but recommended)"
          test -d assets/images || echo "⚠️ Missing assets/images directory (optional but recommended)"
          test -f assets/resume.pdf || echo "⚠️ Missing resume.pdf (optional but recommended)"

  deploy:
    name: Deploy to Netlify
    needs: validate
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          deploy-message: "Deploy from GitHub Actions"